name: Python CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install flake8
        run: |
          pip install flake8

      - name: Run flake8
        run: |
          flake8 .

      - name: Install safety
        run: |
          pip install safety
      
      - name: Run safety check
        run: |
          safety scan
      
      - name: Install bandit
        run: |
          pip install bandit
      
      - name: Run bandit
        run: |
          bandit -r .

